version = 1

[[analyzers]]
name = "python"
enabled = true
meta = { runtime_version = "3.13", dependency_file_paths = ["backend/pyproject.toml"] }

[[analyzers]]
name = "javascript"
enabled = true
meta = { dependency_file_paths = ["frontend/package.json"] }
