sonar.projectKey=heitorpolidoro_sigecon
sonar.organization=heitorpolidoro
sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests,frontend/src
sonar.test.inclusions=**/*.test.tsx,**/*.test.ts,**/tests/**
sonar.exclusions=**/node_modules/**,**/.git/**,**/.venv/**,**/__pycache__/**,**/alembic/versions/**,**/dist/**,**/public/**,**/coverage/**,**/*.html,backend/app/db.py,backend/app/seed*.py
sonar.javascript.exclusions=**/coverage/**
sonar.css.exclusions=**/coverage/**
sonar.cpd.exclusions=**/coverage/**

# Python specific analysis
sonar.python.version=3.13
sonar.python.xunit.reportPath=backend/test-results.xml
sonar.python.coverage.reportPaths=backend/coverage.xml

# JS/TS specific analysis
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.typescript.tsconfigPath=frontend/tsconfig.json
