"""add_is_deleted_to_task

Revision ID: 0aed2b468f19
Revises: 6d23e392b27f
Create Date: 2026-04-21 10:05:19.955216

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0aed2b468f19"
down_revision: str | Sequence[str] | None = "6d23e392b27f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task",
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "is_deleted")
    # ### end Alembic commands ###
