"""add_indexes_to_task_filters

Revision ID: f6d2e0b038d1
Revises: 0aed2b468f19
Create Date: 2026-04-21 10:23:27.693620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f6d2e0b038d1'
down_revision: Union[str, Sequence[str], None] = '0aed2b468f19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_task_assigned_to_id'), 'task', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_task_created_by_id'), 'task', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_task_is_deleted'), 'task', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_task_priority'), 'task', ['priority'], unique=False)
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_index(op.f('ix_task_priority'), table_name='task')
    op.drop_index(op.f('ix_task_is_deleted'), table_name='task')
    op.drop_index(op.f('ix_task_created_by_id'), table_name='task')
    op.drop_index(op.f('ix_task_assigned_to_id'), table_name='task')
    # ### end Alembic commands ###
