name: Migrate

on:
  push:
    branches: [ master ]

jobs:
  migrate:
    name: Run DB Migrations
    runs-on: ubuntu-latest
    env:
      POSTGRES_URL: ${{ secrets.POSTGRES_URL_NON_POOLING }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
    - uses: actions/checkout@v6

    - uses: astral-sh/setup-uv@v8.0.0
      with:
        enable-cache: false
        pyproject-file: backend/pyproject.toml

    - run: uv python install 3.13

    - run: cd backend && uv sync --all-groups

    - run: cd backend && uv run alembic upgrade head
